# Generated by Django 5.1.7 on 2025-04-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
